name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-18.0.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run lint
